[coordinator]
namespace = "/lindb-cluster"
endpoints = ["http://etcd:2379"]

[broker]
[broker.http]
port = 9000

[broker.grpc]
port = 9001

[monitor]
report-interval = "10s"
url = "http://broker2:9000/api/v1/write?db=_internal"

[logging]
dir = "/lindb/broker2"
level = "debug"
