[coordinator]
namespace = "/lindb-cluster"
endpoints = ["http://etcd:2379"]

[storage]
indicator = 1

[storage.grpc]
port = 2891

[storage.wal]
dir = "/lindb/storage1/wal"

[storage.tsdb]
dir = "/lindb/storage1/data"

[monitor]
report-interval = "10s"
url = "http://broker1:9000/api/native/write?db=_internal"

[logging]
dir = "/lindb/storage1"
level = "debug"

