[coordinator]
namespace = "/lindb-cluster"
endpoints = ["http://etcd:2379"]

[storage]
indicator = 3

[storage.grpc]
port = 2891

[storage.wal]
dir = "/lindb/storage3/wal"

[storage.tsdb]
dir = "/lindb/storage3/data"

[monitor]
report-interval = "10s"
url = "http://broker3:9000/api/native/write?db=_internal"

[logging]
dir = "/lindb/storage3"
level = "debug"

