name: Release
on:
  # Mannually trigger
  # Builds binaries only
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  release_package:
    name: Release package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
      - name: Generate release changelog
        id: generate_changelog
        uses: mikepenz/release-changelog-builder-action@v3.7.1
        with:
          configuration: "CHANGELOG/configuration.json"
      - name: Setup Go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
      - name: Build cross platform binaries
        run: bash deploy.sh
      - name: Publish cross platform binaries
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'workflow_dispatch'
        with:
          release_name: ${{ github.ref_name }}
          body: "For installation guides, please check out [Quick start](https://lindb.io/guide/get-started.html).\n${{ steps.generate_changelog.outputs.changelog }}"
          files: |
            release/lindb-*
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Write change log file 
        run: |
          echo "## [${{ github.ref_name }}](https://github.com/lindb/lindb/releases/tag/${{ github.ref_name }}) - ${{ steps.date.outputs.date }}\n" >> 1.txt
          echo "See [code changes](https://github.com/lindb/lindb/compare/${{ steps.generate_changelog.outputs.fromTag}}...${{ steps.generate_changelog.outputs.toTag}}).\n" >> 1.txt
          echo "${{ steps.generate_changelog.outputs.changelog }}\n" >> 1.txt
          echo -e "$(cat 1.txt)$(cat CHANGELOG/CHANGELOG-1.0.md)" > CHANGELOG/CHANGELOG-1.0.md
          cat CHANGELOG/CHANGELOG-1.0.md
      - name: Checkout main 
        run: |
          git fetch origin main
          git checkout main
      - name: Create changelog pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "[chore]: add change logs(${{ github.ref_name }})"
          branch: changelogs
          signoff: true
          delete-branch: true
          title: "[chore]: add change logs(${{ github.ref_name }})"
          body: |
            Add change logs(CHANGELOG/CHANGELOG-1-0.md)
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            release_bot
      - name: Auto merge pull request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
